version: "3.5"

services:
  backend:
    container_name: clean_air_backend
    build:
      context: CleanAIR-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=postgres
      - MQTT_HOST=mqtt
    depends_on:
      - postgres
      - mqtt

  mqtt:
    container_name: mqtt
    build:
      context: mqtt
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

  frontend:
    container_name: clean_air_frontend
    build:
      context: CleanAIR-frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_HOST: postgres
    ports:
      - "80:80"
    depends_on:
      - postgres
      - backend
